### PR TITLE
Use --password-stdin when logging in to remove login over CLI warning

### PR DESCRIPTION
**Pull request by musale**
This PR supersedes #7 to allow running a Codeship build.

### CODE REVIEW

**Comment by drewkit** [comment]
@musale are you not able to target `codeship-library/docker-utilities:password-stdin` branch for your PR?

**Comment by musale** [comment]
@drewkitch sorry, the initial comment you gave on #7 was to target `codeship-library/password-stdin`. Let me change to that ☝️

**Comment by musale** [comment]
@drewkitch sorry to bother you again. Do you mean I use the branch https://github.com/codeship-library/docker-utilities/tree/password-stdin ?

**Comment by drewkit** [comment]
@musale yup!

**Pull request merged**
